# SonarCloud configuration
sonar.organization=usdot-fhwa-stol
sonar.projectKey=usdot-fhwa-stol_carma-analytics-fotda
sonar.sources=src/carma-platform
sonar.tests=src/carma-platform/test
sonar.python.coverage.reportPaths=./coverage.xml
sonar.python.xunit.reportPath=./test-results.xml
sonar.python.version=3.10
sonar.verbose=true
sonar.exclusions=src/carma-platform/test/**, \
src/carma-platform/run_all_control_analysis.py, \
src/carma-platform/environment_scripts.py, \
src/carma-platform/carma_system_resource_usage_plot.py, \
src/carma-platform/run_all_workzone_analysis.py, \
src/carma-platform/run_all_tim_analysis.py, \
src/carma-platform/run_all_regression_analysis.py \
src/carma-platform/message_scripts.py, \
src/carma-platform/utils.py
