#!/usr/bin/env python3

from argparse import ArgumentParser
from dataclasses import dataclass
import math
from pathlib import Path

from matplotlib import pyplot as plt
import more_itertools
import pandas as pd
from scipy.interpolate import splrep, BSpline
from plot_time_to_collision import *

parser = ArgumentParser(
    prog="plot_time_to_collision",
    description="",
)

parser.add_argument(
    "--vehicle-odometry-csv",
    type=Path,
    help="CSV file containing vehicle odometry data",
    required=True,
)

parser.add_argument(
    "--pedestrian-odometry-csv",
    type=Path,
    help="CSV file containing pedestrian odometry data",
    required=True,
)

parser.add_argument("--plots-dir", type=Path, default=Path("plots"))

cli_args = parser.parse_args()

vehicle_odometry_df = parse_vehicle_odometry_from_csv(cli_args.vehicle_odometry_csv)

pedestrian_odometry_df = parse_pedestrian_odometry_from_csv(
    cli_args.pedestrian_odometry_csv
)

times_to_collision_s = get_ttc_timestamps_in_sec(vehicle_odometry_df, pedestrian_odometry_df)

plot_and_save(vehicle_odometry_df, times_to_collision_s, cli_args.plots_dir)